// Sound library configuration for the Noise Desensitizer tool

import type { SoundConfig } from "./noiseTypes";

export const SOUNDS: SoundConfig[] = [
  {
    id: "fireworks",
    label: "Fireworks",
    shortLabel: "Fire",
    icon: "🎆",
    intensityTag: "High",
    fileUrl: "/sounds/fireworks.mp3",
    defaultVolume: 0.2,
    defaultMode: "single",
  },
  {
    id: "thunder",
    label: "Thunder",
    shortLabel: "Thund",
    icon: "🌩️",
    intensityTag: "High",
    fileUrl: "/sounds/thunder.mp3",
    defaultVolume: 0.25,
    defaultMode: "single",
  },
  {
    id: "door_knock",
    label: "Door Knock",
    shortLabel: "Knock",
    icon: "🚪",
    intensityTag: "Medium",
    fileUrl: "/sounds/door_knock.mp3",
    defaultVolume: 0.25,
    defaultMode: "single",
  },
  {
    id: "doorbell",
    label: "Doorbell",
    shortLabel: "Bell",
    icon: "🔔",
    intensityTag: "Medium",
    fileUrl: "/sounds/doorbell.mp3",
    defaultVolume: 0.25,
    defaultMode: "single",
  },
  {
    id: "dog_bark",
    label: "Dog Barking",
    shortLabel: "Bark",
    icon: "🐕",
    intensityTag: "High",
    fileUrl: "/sounds/dog_bark.mp3",
    defaultVolume: 0.2,
    defaultMode: "single",
  },
  {
    id: "baby_crying",
    label: "Baby Crying",
    shortLabel: "Baby",
    icon: "👶",
    intensityTag: "Medium",
    fileUrl: "/sounds/baby_crying.mp3",
    defaultVolume: 0.25,
    defaultMode: "single",
  },
  {
    id: "traffic",
    label: "Traffic/City Noise",
    shortLabel: "Traff",
    icon: "🚗",
    intensityTag: "Medium",
    fileUrl: "/sounds/traffic.mp3",
    defaultVolume: 0.3,
    defaultMode: "single",
  },
  {
    id: "siren",
    label: "Siren",
    shortLabel: "Siren",
    icon: "🚨",
    intensityTag: "Medium",
    fileUrl: "/sounds/siren.mp3",
    defaultVolume: 0.25,
    defaultMode: "single",
  },
  {
    id: "construction",
    label: "Construction/Hammering",
    shortLabel: "Const",
    icon: "🔨",
    intensityTag: "High",
    fileUrl: "/sounds/construction.mp3",
    defaultVolume: 0.2,
    defaultMode: "single",
  },
];
