/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as SelectCharacterRouteImport } from './routes/select-character'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as LogActivityRouteImport } from './routes/log-activity'
import { Route as BumiRouteImport } from './routes/bumi'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as StatsStatTypeRouteImport } from './routes/stats.$statType'
import { Route as QuestsQuestIdRouteImport } from './routes/quests.$questId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCharacterRoute = SelectCharacterRouteImport.update({
  id: '/select-character',
  path: '/select-character',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const LogActivityRoute = LogActivityRouteImport.update({
  id: '/log-activity',
  path: '/log-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BumiRoute = BumiRouteImport.update({
  id: '/bumi',
  path: '/bumi',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestsRoute,
} as any)
const StatsStatTypeRoute = StatsStatTypeRouteImport.update({
  id: '/stats/$statType',
  path: '/stats/$statType',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/$questId',
  path: '/$questId',
  getParentRoute: () => QuestsRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bumi': typeof BumiRoute
  '/log-activity': typeof LogActivityRoute
  '/quests': typeof QuestsRouteWithChildren
  '/select-character': typeof SelectCharacterRoute
  '/thanks': typeof ThanksRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/stats/$statType': typeof StatsStatTypeRoute
  '/quests/': typeof QuestsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bumi': typeof BumiRoute
  '/log-activity': typeof LogActivityRoute
  '/select-character': typeof SelectCharacterRoute
  '/thanks': typeof ThanksRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/stats/$statType': typeof StatsStatTypeRoute
  '/quests': typeof QuestsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/bumi': typeof BumiRoute
  '/log-activity': typeof LogActivityRoute
  '/quests': typeof QuestsRouteWithChildren
  '/select-character': typeof SelectCharacterRoute
  '/thanks': typeof ThanksRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/stats/$statType': typeof StatsStatTypeRoute
  '/quests/': typeof QuestsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/bumi'
    | '/log-activity'
    | '/quests'
    | '/select-character'
    | '/thanks'
    | '/quests/$questId'
    | '/stats/$statType'
    | '/quests/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/bumi'
    | '/log-activity'
    | '/select-character'
    | '/thanks'
    | '/quests/$questId'
    | '/stats/$statType'
    | '/quests'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/bumi'
    | '/log-activity'
    | '/quests'
    | '/select-character'
    | '/thanks'
    | '/quests/$questId'
    | '/stats/$statType'
    | '/quests/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BumiRoute: typeof BumiRoute
  LogActivityRoute: typeof LogActivityRoute
  QuestsRoute: typeof QuestsRouteWithChildren
  SelectCharacterRoute: typeof SelectCharacterRoute
  ThanksRoute: typeof ThanksRoute
  StatsStatTypeRoute: typeof StatsStatTypeRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-character': {
      id: '/select-character'
      path: '/select-character'
      fullPath: '/select-character'
      preLoaderRoute: typeof SelectCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-activity': {
      id: '/log-activity'
      path: '/log-activity'
      fullPath: '/log-activity'
      preLoaderRoute: typeof LogActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bumi': {
      id: '/bumi'
      path: '/bumi'
      fullPath: '/bumi'
      preLoaderRoute: typeof BumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/stats/$statType': {
      id: '/stats/$statType'
      path: '/stats/$statType'
      fullPath: '/stats/$statType'
      preLoaderRoute: typeof StatsStatTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof QuestsRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuestsRouteChildren {
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

const QuestsRouteChildren: QuestsRouteChildren = {
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}

const QuestsRouteWithChildren =
  QuestsRoute._addFileChildren(QuestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BumiRoute: BumiRoute,
  LogActivityRoute: LogActivityRoute,
  QuestsRoute: QuestsRouteWithChildren,
  SelectCharacterRoute: SelectCharacterRoute,
  ThanksRoute: ThanksRoute,
  StatsStatTypeRoute: StatsStatTypeRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
