/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as BumiRouteImport } from './routes/bumi'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrainingModeRouteImport } from './routes/app.training-mode'
import { Route as AppSelectCharacterRouteImport } from './routes/app.select-character'
import { Route as AppQuestsRouteImport } from './routes/app.quests'
import { Route as AppLogActivityRouteImport } from './routes/app.log-activity'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppQuestsIndexRouteImport } from './routes/app.quests.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AppStatsStatTypeRouteImport } from './routes/app.stats.$statType'
import { Route as AppQuestsQuestIdRouteImport } from './routes/app.quests.$questId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const BumiRoute = BumiRouteImport.update({
  id: '/bumi',
  path: '/bumi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingModeRoute = AppTrainingModeRouteImport.update({
  id: '/training-mode',
  path: '/training-mode',
  getParentRoute: () => AppRoute,
} as any)
const AppSelectCharacterRoute = AppSelectCharacterRouteImport.update({
  id: '/select-character',
  path: '/select-character',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppLogActivityRoute = AppLogActivityRouteImport.update({
  id: '/log-activity',
  path: '/log-activity',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsIndexRoute = AppQuestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuestsRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatsStatTypeRoute = AppStatsStatTypeRouteImport.update({
  id: '/stats/$statType',
  path: '/stats/$statType',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsQuestIdRoute = AppQuestsQuestIdRouteImport.update({
  id: '/$questId',
  path: '/$questId',
  getParentRoute: () => AppQuestsRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bumi': typeof BumiRoute
  '/thanks': typeof ThanksRoute
  '/waitlist': typeof WaitlistRoute
  '/app/activity': typeof AppActivityRoute
  '/app/log-activity': typeof AppLogActivityRoute
  '/app/quests': typeof AppQuestsRouteWithChildren
  '/app/select-character': typeof AppSelectCharacterRoute
  '/app/training-mode': typeof AppTrainingModeRoute
  '/app/': typeof AppIndexRoute
  '/app/quests/$questId': typeof AppQuestsQuestIdRoute
  '/app/stats/$statType': typeof AppStatsStatTypeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/quests/': typeof AppQuestsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bumi': typeof BumiRoute
  '/thanks': typeof ThanksRoute
  '/waitlist': typeof WaitlistRoute
  '/app/activity': typeof AppActivityRoute
  '/app/log-activity': typeof AppLogActivityRoute
  '/app/select-character': typeof AppSelectCharacterRoute
  '/app/training-mode': typeof AppTrainingModeRoute
  '/app': typeof AppIndexRoute
  '/app/quests/$questId': typeof AppQuestsQuestIdRoute
  '/app/stats/$statType': typeof AppStatsStatTypeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/quests': typeof AppQuestsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/bumi': typeof BumiRoute
  '/thanks': typeof ThanksRoute
  '/waitlist': typeof WaitlistRoute
  '/app/activity': typeof AppActivityRoute
  '/app/log-activity': typeof AppLogActivityRoute
  '/app/quests': typeof AppQuestsRouteWithChildren
  '/app/select-character': typeof AppSelectCharacterRoute
  '/app/training-mode': typeof AppTrainingModeRoute
  '/app/': typeof AppIndexRoute
  '/app/quests/$questId': typeof AppQuestsQuestIdRoute
  '/app/stats/$statType': typeof AppStatsStatTypeRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/quests/': typeof AppQuestsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bumi'
    | '/thanks'
    | '/waitlist'
    | '/app/activity'
    | '/app/log-activity'
    | '/app/quests'
    | '/app/select-character'
    | '/app/training-mode'
    | '/app/'
    | '/app/quests/$questId'
    | '/app/stats/$statType'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/quests/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bumi'
    | '/thanks'
    | '/waitlist'
    | '/app/activity'
    | '/app/log-activity'
    | '/app/select-character'
    | '/app/training-mode'
    | '/app'
    | '/app/quests/$questId'
    | '/app/stats/$statType'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/quests'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bumi'
    | '/thanks'
    | '/waitlist'
    | '/app/activity'
    | '/app/log-activity'
    | '/app/quests'
    | '/app/select-character'
    | '/app/training-mode'
    | '/app/'
    | '/app/quests/$questId'
    | '/app/stats/$statType'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/quests/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BumiRoute: typeof BumiRoute
  ThanksRoute: typeof ThanksRoute
  WaitlistRoute: typeof WaitlistRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bumi': {
      id: '/bumi'
      path: '/bumi'
      fullPath: '/bumi'
      preLoaderRoute: typeof BumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training-mode': {
      id: '/app/training-mode'
      path: '/training-mode'
      fullPath: '/app/training-mode'
      preLoaderRoute: typeof AppTrainingModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/select-character': {
      id: '/app/select-character'
      path: '/select-character'
      fullPath: '/app/select-character'
      preLoaderRoute: typeof AppSelectCharacterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quests': {
      id: '/app/quests'
      path: '/quests'
      fullPath: '/app/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log-activity': {
      id: '/app/log-activity'
      path: '/log-activity'
      fullPath: '/app/log-activity'
      preLoaderRoute: typeof AppLogActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quests/': {
      id: '/app/quests/'
      path: '/'
      fullPath: '/app/quests/'
      preLoaderRoute: typeof AppQuestsIndexRouteImport
      parentRoute: typeof AppQuestsRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stats/$statType': {
      id: '/app/stats/$statType'
      path: '/stats/$statType'
      fullPath: '/app/stats/$statType'
      preLoaderRoute: typeof AppStatsStatTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quests/$questId': {
      id: '/app/quests/$questId'
      path: '/$questId'
      fullPath: '/app/quests/$questId'
      preLoaderRoute: typeof AppQuestsQuestIdRouteImport
      parentRoute: typeof AppQuestsRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppQuestsRouteChildren {
  AppQuestsQuestIdRoute: typeof AppQuestsQuestIdRoute
  AppQuestsIndexRoute: typeof AppQuestsIndexRoute
}

const AppQuestsRouteChildren: AppQuestsRouteChildren = {
  AppQuestsQuestIdRoute: AppQuestsQuestIdRoute,
  AppQuestsIndexRoute: AppQuestsIndexRoute,
}

const AppQuestsRouteWithChildren = AppQuestsRoute._addFileChildren(
  AppQuestsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppLogActivityRoute: typeof AppLogActivityRoute
  AppQuestsRoute: typeof AppQuestsRouteWithChildren
  AppSelectCharacterRoute: typeof AppSelectCharacterRoute
  AppTrainingModeRoute: typeof AppTrainingModeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStatsStatTypeRoute: typeof AppStatsStatTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppLogActivityRoute: AppLogActivityRoute,
  AppQuestsRoute: AppQuestsRouteWithChildren,
  AppSelectCharacterRoute: AppSelectCharacterRoute,
  AppTrainingModeRoute: AppTrainingModeRoute,
  AppIndexRoute: AppIndexRoute,
  AppStatsStatTypeRoute: AppStatsStatTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BumiRoute: BumiRoute,
  ThanksRoute: ThanksRoute,
  WaitlistRoute: WaitlistRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
